### ISSUE TITLE
Improved Logging

### ISSUE THREAD

**Issue by gregpakes** [kria/TfsNotificationRelay#10]
I was thinking about extending the logging to have log levels.  That way it would be possible to leave logging on without having to create huge log files.

Trace
Info
Warning
Error

Let me know if this would be worthwhile.

**Comment by kria** [comment]
If you mean the Logger class, I don't use that one anymore. 
I use `TeamFoundationApplicationCore.Log` for logging to Windows Logs->Application and `TeamFoundationRequestContext.Trace` for tracing. Take a look at the 1.9.0 [release notes](https://github.com/kria/TfsNotificationRelay/releases) for how to set up a trace (there's a level param as well). You can see how I call those methods in BaseHandler

**Comment by gregpakes** [comment]
Ah ok - I'll take a look.
