### ISSUE TITLE
History / Comments Notifications

### ISSUE THREAD

**Issue by shaneedwards** [kria/TfsNotificationRelay#15]
It would be very beneficial if the notifier would also relay "Discussion Only" history items to slack.  First, this would make it incredibly easy for my developers to keep up with activity on work items even if they don't change state.  Second, this might also replace the lack of @mentions in TFS by allowing developers to @mention slack usernames in the TFS comments.

Great plugin, very much looking forward to implementing for all of our teams!

**Comment by kria** [comment]
`WorkItemComment` event added in the latest release. Unfortunately Slack won't generate a notification on mentions in bot messages, it just highlights the username.

**Comment by shaneedwards** [comment]
Awesome!  I can live with that limitation, thank you very much!

**Comment by shaneedwards** [comment]
I just tested this change out as well.  Works perfectly!  I expect this will smooth out a lot of rough edges in our communication.  Great work!

**Comment by pvandervelde** [comment]
Is there anything special that needs to be done to make this work? I have my own plugin that handles WorkItemCommentNotification but I never get any when I add some text to the history without making any other changes to the work item.

My event rule is:

    <rule notify="true" events="All" teamProjectCollection="" teamProject="" teamName="" gitRepository="" areaPath="" workItemType="" workItemfields="" sourcePath="" buildDefinition="" buildStatuses="All" />

I get notifications when I create an issue or change the state of an issue, but not for comments

**Comment by kria** [comment]
It should work in version 1.11.0 without doing anything special. Which TFS version are you using? Look for any error in the windows application log.

**Comment by pvandervelde** [comment]
I'll have a look in the morning when I'm back at work. We're using TFS2013.4. Is there any way I can turn on a debug log? I found something in the config file but that doesn't seem to put out a debug log that I can tell.

**Comment by pvandervelde** [comment]
The event log to the rescue. I didn't copy the HtmlAgilityPack.dll file. Once I did that I started receiving the comment notifications. Thanks heaps

**Comment by kria** [comment]
Aha! I should update the installation instructions to mention that file. The dependency was added just for extracting text from the html comments.
