### ISSUE TITLE
Tagged Git Commits

### ISSUE THREAD

**Issue by mediafreakch** [kria/TfsNotificationRelay#16]
Is there a way or do you plan to create an event that triggers only when tagged commits are made using GIT? It would allow notifying continues integration services like Jenkins.

**Comment by kria** [comment]
Do you mean you want to implement your own INotifier and use it to notify Jenkins? There's a built in service hook for Jenkins in TFS 2015, if that version is an option for you.

**Comment by mediafreakch** [comment]
Yes, building my own INotifier was the plan to use it for TFS 2013
afterwards, until we upgrade to 2015.

Kristian Adrup <notifications@github.com> schrieb am Di., 7. Juli 2015
15:57:

**Comment by kria** [comment]
You won't really have much use for TfsNotificationRelay if you're just going to invoke Jenkins. You might as well just create your own TFS subscriber. Something like this: https://gist.github.com/kria/209047f536106f75a80f
