### ISSUE TITLE
Filter notifications by git branch name

### ISSUE THREAD

**Issue by Olg-K** [kria/TfsNotificationRelay#18]
Hi!
Is there a way to set up a notification to be sent on push to a specific git branch?
I could only find `gitRepository` attribute in rule configuration, it would be great if a branch name could be specified there as well.

**Comment by kria** [comment]
Currently, it's not possible to filter on git branch. I do have that feature on my todo list though.

**Comment by Olg-K** [comment]
Thanks for the reply @kria!
I'll be following the development.

Thanks for the great plugin!
