### ISSUE TITLE
Add MIT or Apache 2.0 licensing?

### ISSUE THREAD

**Issue by markmbaker** [kria/TfsNotificationRelay#2]
Hello,
Any chance you would dual license your tech with either MIT or Apache 2.0? Can't use the GNU licenses where I work.

Thanks.

**Comment by kria** [comment]
Hi,
I kinda like the GPL for this project. What is it that you want to do? Just using the plugin at your work or modding it without distributing it, doesn't require you to release any source. If you really can't work with GPL software, I could probably sell you a commercial license.
