### ISSUE TITLE
Getting NullReferenceException and 2013/2015 difference

### ISSUE THREAD

**Issue by brgruber** [kria/TfsNotificationRelay#20]
Hey Kria,
I'm working to extend the Notificator to send a message to a server when a build is complete. It is not working, and when I checked the viewer/windows logs/application, I saw this error message:

*Detailed Message: The subscriber TfsNotificationRelay raised an exception while being notified of event Microsoft.TeamFoundation.WorkItemTracking.Server.WorkItemChangedEvent.
Exception Message: Object reference not set to an instance of an object. (type NullReferenceException)
[...] 
c:\repos\TfsNotificationRelay\TfsNotificationRelay\EventHandlers\BaseHandler.cs:line 80*

Apparently, it's a problem in Base Handler, at line 80, which is

 *timer.Start();*

Do u have any idea about what could be making this error to happen?
I also would like to say thanks for your great work in this Notificator. It have been helping me a lot to understand the TFS notification system.
Thank you,
Bruno.

**Comment by kria** [comment]
Well that would happen if timer is null, but the row before that one is `Stopwatch timer = new Stopwatch();` so that doesn't make any sense.

**Comment by brgruber** [comment]
After inspection using log entries, I figured out that the problem is actually in this line:
```javascript
settings = Configuration.TfsNotificationRelaySection.Instance.Settings;
```

**Comment by kria** [comment]
And what exception do you get, a NullReferenceException? Make sure you have DevCore.TfsNotificationRelay.dll.config in the Plugins directory and that the Load_DefaultConfiguration_ShouldSucceed unit test passes.

**Comment by brgruber** [comment]
I just figured out that the problem was in the .config file. After fixing it, the program worked.
I've just one final question: What is the difference between the 2013 and 2015 versions of NotificationRelay? I would like to make my notificator to work in both versions, and if there's no big difference between them, I can just change my current project.
Thank you very much Kria.

**Comment by kria** [comment]
The TFS API changed a bit from TFS 2013 to 2015. Some stuff was renamed or changed namespace. For Git commits, they changed the id from a byte array to a new Sha1Id struct. See what differs between my two versions [here][0].

The code for my notifiers is the same for both versions, but you probably need to recompile against 2015 assemblies.

[0]:https://github.com/kria/TfsNotificationRelay/compare/cb3e046e9699457e340bab3a3181b95be605c409...8bfdcaec231088b8252a55f41b85d5961b373ec6

**Comment by brgruber** [comment]
Okay, thank you very much Kria!
