### ISSUE TITLE
vNext build notification

### ISSUE THREAD

**Issue by kria** [kria/TfsNotificationRelay#21]
vNext builds aren't generating any notifications. Hopefully they've added a new event to subscribe to.

**Comment by jimschubert** [comment]
I don't seem to be getting any notifications in HipChat for TFS 2015 RTM.

**Comment by kria** [comment]
Are you not getting any notifications at all? Make sure you are using the tfs2015 build and check your eventlog for any error messages.

If you mean vNext build notifications specifically, then no they don't work and I'm looking into it.

**Comment by jimschubert** [comment]
I can't seem to get any notifications. I'll check again that I didn't use
the 2013 binaries.

**Comment by jimschubert** [comment]
j/k. I am getting notifications ;)

I dropped the plugin into Tools\Plugins by accident. Moved it to the right directory and everything but Build Preview notifications are working as I would expect.

**Comment by jimschubert** [comment]
I should add that not everything was 100%.  I *did* have to do an assembly binding redirect on HtmlAgilityPack in the config file:

        <dependentAssembly>
          <assemblyIdentity name="HtmlAgilityPack" publicKeyToken="bd319b19eaf3b43a" culture="neutral" />
          <bindingRedirect oldVersion="0.0.0.0-1.4.9.9" newVersion="1.4.6.0" />
        </dependentAssembly>

We installed TFS RC2, then updated to RTM. The version of HtmlAgilityPack from the 1.12 TFS2015 release is 1.4.9.0 while our TFS installation has already loaded 1.4.6.0, which causes an error in the event log.  I wanted to comment in case anyone else had the issue, but I haven't had time to track down what's loading the older version of HtmlAgilityPack. The binding redirect seems to work fine, though.

**Comment by kria** [comment]
Good stuff!
I get that error too, it doesn't stop the plugin from working though. I'll get rid of it for next release.
