### ISSUE TITLE
Logging not working in TFS 2015

### ISSUE THREAD

**Issue by gregpakes** [kria/TfsNotificationRelay#22]
I recently upgraded to TFS 2015 and am now trying to get TFSNotificationRelay to work.  It's not working, but when I try and enable tracing with the following.

```sql
DECLARE @traceId UNIQUEIDENTIFIER = NEWID() 
EXEC prc_CreateTrace @traceId = @traceId, @area = 'TfsNotificationRelay'
```

Nothing happens.  No log is created.

**Comment by kria** [comment]
Hi Greg,
If it's not working at all you should be getting some kind of error message in the regular event log. If you're getting nothing there, make sure you downloaded the latest 2015 release and deployed to the correct directory (C:\Program Files\Microsoft Team Foundation Server 14.0\Application Tier\Web Services\bin\Plugins) and not the old 12.0 directory. Try with a fresh config file.

Regarding the trace, make sure IsEnabled=1 in tbl_Trace. I think traces are disabled on upgrade. The trace is located in ```Event Viewer/Application and Service Logs/Microsoft-Team Foundation Server/Debug```.

**Comment by gregpakes** [comment]
Much appreciated.  I've updated the wiki and added a logging section.  Hope that's ok.

**Comment by gregpakes** [comment]
It doesn't seem to be quite as simple.  I found an error in the config file (I was using BuildFailed which has been removed).  I fixed that, but now I get nothing at all in either of the event logs, but also no alerts.

I have made sure IsEnabled is 1.  I have also restarted all services.

**Comment by kria** [comment]
Did you get an error in the event log before you fixed the config, and now you get no error (and no notifications)?

**Comment by gregpakes** [comment]
Yes and Yes

**Comment by kria** [comment]
That's unpossible! :)
You're using the 2015 variant of v1.13.0?
You're running 2015 RTM (not an RC)?

**Comment by gregpakes** [comment]
Yes and Yes.  I can get errors by putting an error in the config file.  I then get an error in the event log saying that the config file is wrong.  I'm still testing so I'll let you know what I find.

**Comment by gregpakes** [comment]
Ok - I've fixed it by comparing the latest config file with mine.  In the **rule** element, I needed to add entries for workItemfields, buildStatuses, sourecPath, areaPath and workItemType.

I suspect **buildStatues** was the one I really needed.  I am monitoring **buildCompleted** event and hadn't set the **buidStatuses**.

Sound right?

**Comment by kria** [comment]
Yeah set that to ```Failed``` If you just want the failed builds.

```buildStatuses takes a comma-separated list of: None, InProgress, Succeeded, PartiallySucceeded, Failed, Stopped, NotStarted, All```

**Comment by gregpakes** [comment]
Appreciate the support.

**Comment by kria** [comment]
You got it working?
No problem! Backwards compatibility hasn't really been a priority, so upgrading can be a bit of a hassle, even though I try to document the changes in the release description.

**Comment by gregpakes** [comment]
Still haven't got the basic trace working - but I no longer need it.  Nothing appears in the log when I turn tracing on.
