### ISSUE TITLE
Reliable Tracing in 2015

### ISSUE THREAD

**Issue by gregpakes** [kria/TfsNotificationRelay#23]
Hi,

I still can't get reliable tracing.  I'm trying to debug an issue by using the tracing, but whenever I make a change to the config and save, I then get nothing in either the Application Log or the TFS log.

I am triggering events and monitoring the logs, but nothing appears at all.  I would have expected to either see an error loading the plugin in the Application Log or start seeing the "ProcessEvent" trace notifications in the TFS log.

Do you have any ideas?

FYI - Alerts aren't coming through either.  I think the plugin is failing somewhere, but I get no alerts.

**Comment by kria** [comment]
I changed the ProcessEvent trace from Verbose to Info, maybe you're not missing it in the clutter? You see other events (like TFS JobAgentHistory Entry) in the TFS trace log, right?
You can filter out only TfsNotificationRelay events using:
```
<QueryList>
  <Query Id="0" Path="Microsoft-Team Foundation Server/Debug">
    <Select Path="Microsoft-Team Foundation Server/Debug">*[UserData[Info[(Area='TfsNotificationRelay')]]]</Select>
  </Query>
</QueryList>
```

You had notifications working earlier, what happened? Are you trying something new in the configuration that stops it from working?

**Comment by gregpakes** [comment]
Hi - I am using the search feature in the event log.  Nothing is being logged.  Yes I see other logs, lots of them.

I recompiled the source with some more trace commands.  I seem to be in some state where I get no logs at all.  I will keep trying.

**Comment by gregpakes** [comment]
My mistake...  *hangs head in shame*

I was compiling the 2013 version rather than 2015.

----

Incidentally, I am adding extra tracing logging for debugging the regexes to see what exactly is being tested.  Is this something you would like a PR for?

**Comment by kria** [comment]
Hah, it's always something. I was looking into the tracing earlier and couldn't get new events to show up. It took way too long to realize that I was building the Release configuration but deploying an old Debug build. :blush: 

Sure, send a PR. Tracing is really underutilized in the project.
