### ISSUE TITLE
Moving to C# 6

### ISSUE THREAD

**Issue by kria** [kria/TfsNotificationRelay#24]
I'd like to start using all the neat C# 6 features (in both the 2013 and 2015 branches). This means that Visual Studio 2015 will be needed in order to build the source. The project will still target .NET 4.5. 

If someone has a problem with this, speak up!

**Comment by gregpakes** [comment]
Sounds good to me.  I've been avoiding them in my current PR.  Shall I start using them?

**Comment by kria** [comment]
Nah, keep it to C# 5 for now.
