### ISSUE TITLE
TFS 2015 Update 1 support

### ISSUE THREAD

**Issue by kria** [kria/TfsNotificationRelay#27]
There are a few major [breaking changes][0] in Update 1. 

[0]: http://blogs.msdn.com/b/visualstudioalm/archive/2015/10/13/breaking-change-in-tfs-2015-update-1-for-server-side-plugins.aspx

**Comment by gregpakes** [comment]
Any news on Update 1 support?

**Comment by kria** [comment]
I thought I'd wait for the final to release it, but it works and you can build the tfs2015.1 branch yourself.

**Comment by kria** [comment]
Update 1 support released in [v1.15.0](https://github.com/kria/TfsNotificationRelay/releases/tag/v1.15.0).
