### ISSUE TITLE
Multiple entries in output Slack channel

### ISSUE THREAD

**Issue by PeMur** [kria/TfsNotificationRelay#28]
We have been using the Slack integration for a few months with some success.  A week ago we updated to v1.13, and started receiving triplicate entries in the channel for each update.  Today we tried 1.14, and now are getting four entries for each update.  The config file, which has separate bots - sharing one webhookUrl value - for each event, didn't change in between 1.13 and 1.14. 

Is there a step in the install routine that I've missed, or some other oversight on my part?

**Comment by kria** [comment]
Do you mean that you get four _identical_ notifications? 
Can you e-mail me the config at subsurfer@gmail.com (remove webhook url). 
Which version did you use before 1.13 that worked?
Which TFS version?

**Comment by kria** [comment]
If anyone else runs into this, the problem was that previous versions of the plugin had been stashed in a subdirectory of ```\Plugins```, so they would also be loaded.
