### ISSUE TITLE
TFS 2015.1 + Sack Integration not working

### ISSUE THREAD

**Issue by elryry** [kria/TfsNotificationRelay#33]
Hi, I am trying to configure TfsNotificationRelay with TFS 2015.1 and Slack. I have followed the Installation guide from the Wiki word-for-word as well as enabled logging, and I am having no luck (also getting no logs).

I had a few questions regarding the configuration:

1. Does the teamProjectCollection value support spaces? Is this a valid value: "My Collection" or is it looking for the URL value https://tfsserver/My%20Collection?
2. Same as 1 for teamProject, are spaces valid? Is this a valid value: "My Project" or is it looking for the relative command-line value $/My%20Project?
3. Can teamName be left empty if I don't want to restrict/filter to that level?

Thanks for any help you could provide!

**Comment by elryry** [comment]
I finally got something to show up in the logs:

Log Name:      Microsoft-Team Foundation Server/Debug
Source:        Microsoft-Team Foundation Server
Date:          12/16/2015 10:28:21 AM
Event ID:      0
Task Category: This task has debugging events
Level:         Error
Keywords:      Info Messages
User:          ---------------
Computer:      ---------------
Description:
ReflectionTypeLoadException loading assembly: DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null. Not all plugins may be loaded. Exception Details: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.TeamFoundation.Framework.Server.VssExtensionManagementService.ExportTypeMap.FillInExtensionRefsFromAssembly(Assembly a, Object typeMapLock, IDictionary`2 typeMap, Boolean reportErrors). Loader Exceptions: TF400443: Failure loading extensions of type DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null.
Plugin directory = D:\Program Files\Microsoft Team Foundation Server 14.0\Application Tier\TfsJobAgent\Plugins.

Loader Exception(s):
Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.BuildCompletedHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.BuildCompletedHandler

Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.BuildCompletionHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.BuildCompletionHandler

Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.BuildQualityChangedHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.BuildQualityChangedHandler

Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.CheckinHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.CheckinHandler

Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.DiscussionsHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.DiscussionsHandler

Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.PullRequestCreatedHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.PullRequestCreatedHandler

Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.PullRequestReviewerVoteHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.PullRequestReviewerVoteHandler

Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.PullRequestStatusUpdateHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.PullRequestStatusUpdateHandler

Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.RepositoryCreatedHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.RepositoryCreatedHandler

Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.ProjectCreatedHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.ProjectCreatedHandler

Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.ProjectDeletedHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.ProjectDeletedHandler

Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.WorkItemChangedHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.WorkItemChangedHandler

Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.GitPushHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.GitPushHandler


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Team Foundation Server" Guid="{80761876-6844-47D5-8106-F8ED2AA8687B}" />
    <EventID>0</EventID>
    <Version>3</Version>
    <Level>2</Level>
    <Task>1</Task>
    <Opcode>10</Opcode>
    <Keywords>0x8000000000000001</Keywords>
    <TimeCreated SystemTime="2015-12-16T16:28:21.013452700Z" />
    <EventRecordID>1334058</EventRecordID>
    <Correlation ActivityID="{0EB4F1C4-C5AC-48CB-B8DA-45EAA33F1D52}" />
    <Execution ProcessID="8488" ThreadID="4988" />
    <Channel>Microsoft-Team Foundation Server/Debug</Channel>
    <Computer>------------</Computer>
    <Security UserID="------------" />
  </System>
  <UserData>
    <Info TraceId="{00000001-0001-0001-0000-000000000000}  " xmlns="http://schemas.microsoft.com/TeamFoundation/2010/Framework">
      <Tracepoint>63927</Tracepoint>
      <ServiceHost>{00000000-0000-0000-0000-000000000000}</ServiceHost>
      <ContextId>0</ContextId>
      <ProcessName>TfsJobAgent</ProcessName>
      <Username>
      </Username>
      <VSID>{00000000-0000-0000-0000-000000000000}</VSID>
      <Service>
      </Service>
      <Method>
      </Method>
      <Area>VssExtensionManagementService</Area>
      <Layer>Service</Layer>
      <UserAgent>
      </UserAgent>
      <Uri>
      </Uri>
      <Path>
      </Path>
      <UniqueIdentifier>{00000000-0000-0000-0000-000000000000}</UniqueIdentifier>
      <UserDefined>
      </UserDefined>
      <ExceptionType>
      </ExceptionType>
      <Message>ReflectionTypeLoadException loading assembly: DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null. Not all plugins may be loaded. Exception Details: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.TeamFoundation.Framework.Server.VssExtensionManagementService.ExportTypeMap.FillInExtensionRefsFromAssembly(Assembly a, Object typeMapLock, IDictionary`2 typeMap, Boolean reportErrors). Loader Exceptions: TF400443: Failure loading extensions of type DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null.
Plugin directory = D:\Program Files\Microsoft Team Foundation Server 14.0\Application Tier\TfsJobAgent\Plugins.

Loader Exception(s):
Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.BuildCompletedHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.BuildCompletedHandler

Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.BuildCompletionHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.BuildCompletionHandler

Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.BuildQualityChangedHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.BuildQualityChangedHandler

Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.CheckinHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.CheckinHandler

Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.DiscussionsHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.DiscussionsHandler

Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.PullRequestCreatedHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.PullRequestCreatedHandler

Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.PullRequestReviewerVoteHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.PullRequestReviewerVoteHandler

Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.PullRequestStatusUpdateHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.PullRequestStatusUpdateHandler

Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.RepositoryCreatedHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.RepositoryCreatedHandler

Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.ProjectCreatedHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.ProjectCreatedHandler

Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.ProjectDeletedHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.ProjectDeletedHandler

Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.WorkItemChangedHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.WorkItemChangedHandler

Loader Exception Type: System.TypeLoadException
Message: Method 'ProcessEvent' in type 'DevCore.TfsNotificationRelay.EventHandlers.GitPushHandler' from assembly 'DevCore.TfsNotificationRelay, Version=1.14.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Failed to load type: DevCore.TfsNotificationRelay.EventHandlers.GitPushHandler

</Message>
    </Info>
  </UserData>
</Event>

**Comment by kria** [comment]
Hi @elryry,
No currently released version of TfsNotificationRelay supports TFS 2015.1. You'll have to build it yourself from the tfs2015.1 branch or wait until I get around to making a new release. See issue #27.

1+2: I think space should work.
3: Yes, it can be left empty.

**Comment by elryry** [comment]
@kria thanks for the response. In the 2015.1 branch, the Microsoft.TeamFoundation.Common and Microsoft.VisualStudio.Services.WebApi dlls are missing from the lib folder. Is it safe to assume I can just grab those from VS 2015 and TFS 2015 installs to build successfully?

**Comment by elryry** [comment]
Just to update, I built 2015.1 branch and redeployed the .dlls and .config files. Not getting the same error as above, however it is still not sending any notifications to my Slack channel.

**Comment by kria** [comment]
Maybe you'll have better luck with the [latest release](https://github.com/kria/TfsNotificationRelay/releases/tag/v1.15.0) which supports 2015.1, if you haven't already gotten it to work.
