### ISSUE TITLE
Not loading at all

### ISSUE THREAD

**Issue by PeterKottas** [kria/TfsNotificationRelay#35]
Hi, first of all, congrats on a useful tool you build kria. I like the structure and it seems config should be pretty powerful as well. I've just got one small problem with it. It does nothing ! :D 
I followed the instructions carefully. All is copied where it should be. Config file is setup with my unique webhook (I am trying to use it with slack) but I see nothing. I've enabled logfile but it's not even created. What would you recommend to check? We have 12.0.40629.0 (Tfs2013.Update5) installed.

**Comment by kria** [comment]
Make sure the files are copied to `C:\Program Files\Microsoft Team Foundation Server 12.0\Application Tier\Web Services\bin\Plugins` and that you use the tfs2013 zip (and not the tfs2015 one).

If you've done that and nothing happens you should see something in the event viewer. Look in Windows Logs->Application for an error from the TFS Services source.

**Comment by PeterKottas** [comment]
Hi mate, sry notification for your message went to spam so I didn't catch it. Only now when you closed it. I didn't manage to make it work. Might have been because our tfs is installed on non system drive and it's missing some dll. Logs for application says nothing as well. Very odd indeed but we have decided to move to team city (unrelated to this of course) so you might look into this if somebody else ever get this problem. Thanks for the reaction anyways.
