### ISSUE TITLE
TFS 2015.1 notification Not after vNext Builds, only after XAML

### ISSUE THREAD

**Issue by StanleyOK** [kria/TfsNotificationRelay#37]
Thank you for developing TfsNotificationRelay – very interesting tool for TFS,
but I there's problem with vNext builds.
I’ve installed TfsNotificationRelay v1.15.0 on TFS 2015.1.
but it sends post on Slack **only after  XAML builds **
**After vNext build:  no post on Slack  and error in Event Viewer:**

**TF53010:** The following error has occurred in a Team Foundation component or extension:
. . .
Detailed Message: TfsNotificationRelay: **Notify failed for bot slack5.**
Exception Stack Trace:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at DevCore.TfsNotificationRelay.Slack.SlackNotifier.<>c.<NotifyAsync>b__0_0(Task`1 t)
. . . 
Exception Message: **A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond** …:…  (type SocketException) . . .
Full error from Event Log:
[VNext_Slack_ERROR.txt](https://github.com/kria/TfsNotificationRelay/files/188057/VNext_Slack_ERROR.txt)
My system: TFS server:  Windows Server 2012 R2 Standard,
                   TFS 2015 14.0.24712.0 (Tfs2015.Update1);  SQL Server 2014 (64-bit)
Build machines: Windows Server  2008 R2 Standard,   TFS 2012 Up. 2

What's your guess - why it works for XAML builds only ?

**Comment by kria** [comment]
I would guess that you have changed the url in the config file since restarting `Visual Studio Team Foundation Background Job Agent`. The config changes are picked up automatically by the standard plugin in `Application Tier\Web Services\bin\Plugins`, but that is not the case for the plugin in `Application Tier\TFSJobAgent\Plugins`. So restart the TfsJobAgent.

**Comment by StanleyOK** [comment]
Thanks, I will ty it. The config in  `Application Tier\Web Services\bin\Plugins` (for XAML) and config in  `Application Tier\TFSJobAgent\Plugins` (for vNext) have the same value of url (`webhookUrl`). Maybe these values shouldn't be equal ?

**Comment by kria** [comment]
1. You actually only need one config file. If there is no config in `Application Tier\TFSJobAgent\Plugins`, it will be read from `Application Tier\Web Services\bin\Plugins`.

2. I don't think the plugin will auto-detect proxy settings. For it to use a proxy, you need to have a `<defaultproxy>` in `Application Tier\Web Services\web.config` and `Application Tier\TFSJobAgent\TfsJobAgent.exe.config` (for vNext builds).

**Comment by StanleyOK** [comment]
It works now, thank you.

**Comment by kria** [comment]
Glad to hear it!
