### ISSUE TITLE
Highlight Notification cann't work

### ISSUE THREAD

**Issue by yaochangyu** [kria/TfsNotificationRelay#40]
My configuration by userMaps
Below screen shot
![2016-04-07_23-31-24](https://cloud.githubusercontent.com/assets/12044902/14372180/c9f6130e-fd70-11e5-9256-7998413c38ca.jpg)

Result below, It have no highlight
![2016-04-08_09-43-16](https://cloud.githubusercontent.com/assets/12044902/14371941/c8cd1b78-fd6e-11e5-9fc6-75eb1568eb24.jpg)

Full DevCore.TfsNotificationRelay.dll.config on below
[DevCore.TfsNotificationRelay.dll.txt](https://github.com/kria/TfsNotificationRelay/files/209512/DevCore.TfsNotificationRelay.dll.txt)

ref:
https://github.com/kria/TfsNotificationRelay/issues/25
https://github.com/kria/TfsNotificationRelay/wiki/Installation

**How to do can display highlight or "@" in Slack?**

**Comment by kria** [comment]
Hi yaochangyu,

Thanks for the detailed report. Besides adding a user to the usermap, you need to change `buildFormat` and `build2015Format` to something like `triggered by &lt;@{mappedUser}&gt;` to get the highlight. See the example in the [latest release notes](https://github.com/kria/TfsNotificationRelay/releases/tag/v1.15.0).

**Comment by yaochangyu** [comment]
Thanks,
I got it.
