### ISSUE TITLE
Only getting TFS Build Notifications in Slack

### ISSUE THREAD

**Issue by cytron201** [kria/TfsNotificationRelay#42]
Hi, this is almost certainly a config issue, so i'd appreciate some help please....

Using TFS 2015 Update 2, patch 1.

Installed as directed on Wiki page for vNext Builds and regular TFS interaction. Currently only getting personal DMs for build statuses, nothing for Work Item assignments etc.
Using default configuration as follows:

      <bot id="slackdm" type="DevCore.TfsNotificationRelay.Slack.DirectMessageNotifier, DevCore.TfsNotificationRelay.Slack" textId="slacktext" userMapId="slackusers">
        <botSettings>
          <add name="token" value="XXXXXXXXXXTOKEN HEREXXXXXXXXXXX" />
          <add name="standardColor" value="#68217a" />
          <add name="successColor" value="#1cb841" />
          <add name="errorColor" value="#ca3c3c" />
          <add name="wiCreatedDisplayFields" value="System.AreaPath, System.IterationPath, System.State, System.Reason, System.AssignedTo"/>
          <add name="wiChangedDisplayFields" value="System.AreaPath, System.IterationPath, System.State, System.Reason, System.AssignedTo"/>
        </botSettings>
        <eventRules>
          <rule notify="true" events="All" teamProjectCollection="" teamProject="" teamName="" gitRepository="" gitBranch="" gitTag="" areaPath="" workItemType="" workItemfields="System.State, System.AssignedTo" sourcePath="" buildDefinition="" buildStatuses="All" />
        </eventRules>
      </bot>

**Comment by kria** [comment]
DirectMessageNotifier is very different from SlackNotifier. For most events it won't send any notification at all. The thinking was that If I caused the event and it doesn't give me anymore information, I don't want a DM about it.

DirectMessageNotifier looks at a property called TargetUserNames on the Notification to determine which users to send to. For work items it looks like this:
```
public override IEnumerable<string> TargetUserNames
{
	get
	{
		if (AssignedToUniqueName != null && AssignedToUniqueName != UniqueName)
			return new[] { AssignedToUniqueName };
		else
			return Enumerable.Empty<string>();
	}
}
```
So you would only get a DM if the work item is assigned to you, and someone other than you changed it.

**Comment by cytron201** [comment]
Yea, that's exactly what i expected, but if i assign a Bug to a team member for example, they arent getting notified by Slack DM bot.

Agreed that i wouldnt want a DM about assigning something to myself, that's expected behaviour based on how the emails work

**Comment by kria** [comment]
Do you have a regular SlackNotifier that sends a notification to a channel, in that case when you assign a bug to a team member? Just to make sure that the event works.

**Comment by cytron201** [comment]
Not enabled no, i'll try that and report back.... thanks!

**Comment by kria** [comment]
Maybe you just copied the dll:s to `TFSJobAgent\Plugins` (needed for vNext builds) and not to `Web Services\bin\Plugins` (needed for everything else)?

**Comment by cytron201** [comment]
Nope, they're in both - Just tested the Post to Channel bot, and it correctly posted that a Bug had been assigned to a user

**Comment by kria** [comment]
And the target user does get a DM from a build notification? So it's not a user mapping problem.

**Comment by cytron201** [comment]
Yes that's working fine, all users say they get Build DMs

**Comment by kria** [comment]
You only have one .config file and it's in `Web Services\bin\Plugins`?

**Comment by cytron201** [comment]
One in Web Services\bin\Plugins and one in TFSJobAgent\Plugins

**Comment by kria** [comment]
I was thinking that the user mapping might differ between the files. You only need one in `Web Services\bin\Plugins`. It will look there if it's missing in `TFSJobAgent\Plugins`.

**Comment by kria** [comment]
Btw the vNext build events will only pick up config changes after a restart of Visual Studio Team Foundation Background Job Agent.

**Comment by kria** [comment]
Hmm I don't have any good idea, did you check the windows app log for any errors?

**Comment by cytron201** [comment]
Build notifications were fine, but I've now deleted the .config in that folder (it was a direct copy), so it's good to know I only need to update one now.

Nothing i can see in App log either, no errors :-/

Thanks very much for the help, i'll keep updated with versions, maybe it will work in future with our collection

**Comment by kria** [comment]
It looks like this is broken because of a change of the user format between 2015 RC and RTM. I only compensated for this change in the display name and forgot the target user comparison. I'll try to get you new release that works.

**Comment by cytron201** [comment]
Great that you found the bug! Phew.

Cool, good news, will look forward to that, cheers

**Comment by kria** [comment]
I just uploaded a [new release](https://github.com/kria/TfsNotificationRelay/releases/tag/v1.15.1), hopefully it solves your problem.

**Comment by cytron201** [comment]
Works like a charm! Thanks very much for the fast action, that's a great help!
