### ISSUE TITLE
Filtering out changeset comments from work item comments

### ISSUE THREAD

**Issue by guillaumeviel** [kria/TfsNotificationRelay#48]
The ability to send work item comments (WorkItemComment) is great but the value is diluted as we can get flooded with changeset comments associated these work items.

Example:

> Tom commented on Product Backlog Item #35367 - xxxxxxxx
> Comment
> Associated with changeset 10892: xxxxxxxxx

Would it be possible to add an option to filter the changeset comments out, so that we only receive real work items comments?

**Comment by kria** [comment]
Text filtering has been added, check out the example in the [latest release](https://github.com/kria/TfsNotificationRelay/releases/tag/v1.17.0).

**Comment by guillaumeviel** [comment]
Thanks a lot for this!
