### ISSUE TITLE
Events not firing on certain team projects

### ISSUE THREAD

**Issue by ernestopye** [kria/TfsNotificationRelay#5]
Hey kria,

First of all I wanted to really thank you for your work! TfsNotificationRelay is great and we're having good success with it for the most part.

We have 3 team projects. I've set up the regex for them and have gone from very specific to very broad catch-all regexes to see if it makes a difference, but it doesn't seem to.

2 of the projects send out the alerts just fine. 1 one of them remains stubborn. The only difference that jumps out between these is the project template. The team project giving us issues was set up over a year ago with a different template (and in fact, under an older version of TFS, I think it was 2012) than the other two (both of which work just fine). Do you have any idea if this could affect which events are dispatched to TfsNotificationRelay, and if so, if there's a way to ensure these are set up?

We're currently running TFS 2013.2. If there's anything I can do on my end to troubleshoot this let me know.

Thanks for any help, and thanks again for your work on this!

**Comment by kria** [comment]
I would very surprised if TFS doesn't fire events for a all team projects. I think it's more likely that my plugin is breaking for some reason on that specific team project. Which events are you expecting? 

Can you take a look in event viewer/windows logs/application on the TFS server and look for any Error level event from TFS Services. The message will be something like *The subscriber TfsNotificationRelay raised an exception while being notified of event...*

**Comment by ernestopye** [comment]
The bot is currently set up to relay all events. A detail I forgot to mention is that check-in notifications do work on all team projects. It's only work item-related events that aren't being sent. Something like creating a bug or changing its status is the easiest way I've found to replicate it on our end.

Looks like you were correct. I had IT take a look at TFS logs and he found the following:

TF53010: The following error has occurred in a Team Foundation component or extension:
Date (UTC): 3/23/2015 11:09:13 AM
Machine: <snip>
Application Domain: <snip>
Assembly: Microsoft.TeamFoundation.Framework.Server, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a; v4.0.30319
Service Host: <snip>
Process Details:
  Process Name: w3wp
  Process Id: 2652
  Thread Id: 2912
  Account name: <snip>

Detailed Message: The subscriber TfsNotificationRelay raised an exception while being notified of event Microsoft.TeamFoundation.WorkItemTracking.Server.WorkItemChangedEvent.
Exception Message: Object reference not set to an instance of an object. (type NullReferenceException)
Exception Stack Trace:    at DevCore.TfsNotificationRelay.EventHandlers.WorkItemChangedHandler.CreateNotification(TeamFoundationRequestContext requestContext, WorkItemChangedEvent ev, Int32 maxLines)
   at DevCore.TfsNotificationRelay.EventHandlers.BaseHandler.ProcessEvent(TeamFoundationRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties)
   at Microsoft.TeamFoundation.Framework.Server.TeamFoundationEventService.SubscriptionList.Notify(TeamFoundationRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, String& statusMessage, ExceptionPropertyCollection& properties)

Hopefully this is useful to you. IT will get me some more error messages later in the day, so I'll be sure to post those here for you when they come back.

Thanks so much!

**Comment by ernestopye** [comment]
I got a bunch more of these logs from IT just now, but they seem to point to the same code as above. Hopefully you're able to figure this out. If there's anything else we can do to help let me know.

**Comment by kria** [comment]
I can't tell what the problem is from that stack trace. If you download this [debug build](https://github.com/kria/TfsNotificationRelay/releases/download/v1.9.0/TfsNotificationRelay-v1.9.0-debug.zip) and drop in the dll and pdb files in the Plugins dir, I can hopefully pinpoint the problem in a new stack trace.

**Comment by ernestopye** [comment]
Just wanted to let you know what IT's been swamped here and I sadly don't have access to the TFS servers, so I can't do this myself, but I'm still looking to help resolve this. I'm trying to get them to lend us their time maybe next week.

**Comment by ernestopye** [comment]
Go figure, as soon as we get the debug build in place, we stop being able to see errors being logged. We just simply couldn't get them to come up, and we still only see check-in notifications from this one team project. We even reverted back to the release build and we still couldn't see any errors. 

I couldn't do this myself, but I'm putting my trust in IT that they checked the same location as before. Not sure what else to do to help at this point.
