### ISSUE TITLE
TFS2017 Notify failed for bot hipchat

### ISSUE THREAD

**Issue by kleeklee** [kria/TfsNotificationRelay#50]
using 1.17.0 for TFS 15 receiving the following when a notification attempts to send.
Was working fine in TFS2015 with previous notifcationrelay version, prior to upgrading to TFS 2017

Detailed Message: TfsNotificationRelay: Notify failed for bot hipChat.
Exception Message: One or more errors occurred. (type AggregateException)
Exception Stack Trace:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at DevCore.TfsNotificationRelay.HipChat.HipChatNotifier.<>c.<NotifyAsync>b__0_0(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DevCore.TfsNotificationRelay.HipChat.HipChatNotifier.<NotifyAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DevCore.TfsNotificationRelay.EventHandlers.BaseHandler.<NotifyAsync>d__11.MoveNext()

Inner Exception Details:

Exception Message: An error occurred while sending the request. (type HttpRequestException)
Exception Stack Trace: 

Inner Exception Details:

Exception Message: The underlying connection was closed: An unexpected error occurred on a send. (type WebException)Exception Stack Trace:    at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)

Inner Exception Details:

Exception Message: Authentication failed because the remote party has closed the transport stream. (type IOException)
Exception Stack Trace:    at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)

**Comment by kria** [comment]
Is this cloud or on-premises? The error message makes me think TLS 1.0 is not supported on the remote. Odd that it worked before though, unless something just changed on the HipChat end. You don't have .NET 4.6 or higher installed on the TFS server I assume?

**Comment by kleeklee** [comment]
It's on-premise and our Hipchat is also on-premise.  Latest hipchat server version was working with TFS2015 up until we to 2017. So no changes since have been made to the hipchat server.
Actually have up to 4.6.1 installed.

**Comment by kleeklee** [comment]
I noticed this on hipchat site
HipChat Server 2.0 build 2.0.7 – November 08, 2016 - Production channel
Promoted from beta to production on November 16th, 2016.
If you're upgrading from HipChat Server version 1.3 or older you will need at least 5GB of free disk space on the root partition and it will take at least 60 minutes to complete, and will require a reboot afterwards.
Fixes:
Upgraded internal Atlassian Crowd to 2.10.  See Crowd 2.10.1 Release Notes  for more information.
Upgraded bundled android client to version 3.15.054.
**TLS 1.0 fallback support has been removed.**

src: https://confluence.atlassian.com/hc/hipchat-server-release-notes-608731400.html

**Comment by kria** [comment]
If you don't mind building it yourself you can try [this fix](https://github.com/kria/TfsNotificationRelay/tree/tlstest) to force TLS 1.1 or 1.2.

**Comment by kleeklee** [comment]
Thanks! I'll give that a shot.

**Comment by kleeklee** [comment]
It works! Thank you!

**Comment by kria** [comment]
Cool! Can you do me a favor and change it to this to see if it still works if TLS 1.0 is also enabled?
```
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
```

**Comment by kleeklee** [comment]
Yup still works!
