### ISSUE TITLE
No support TFS 2017 update1?

### ISSUE THREAD

**Issue by yaochangyu** [kria/TfsNotificationRelay#55]
Hi,
If I upgrade to update1, I will not receive notification from the TfsNotificationRelay.

**Comment by kria** [comment]
There are some breaking changes (#53), but I don't know how the current version will behave tbh. Hopefully I'll get a 2017.1 release out in not too long.

**Comment by kria** [comment]
TFS 2017.1 support released in [v1.18.0](https://github.com/kria/TfsNotificationRelay/releases/tag/v1.18.0).
