### ISSUE TITLE
GitPush with gitRepository filter not working well

### ISSUE THREAD

**Issue by guillaumeviel** [kria/TfsNotificationRelay#56]
Hi,

I can't get the "GitPush" event to work in combination with the "gitRepository" filter.

Here is what works and what doesn't work:
 - "GitPush" without the "gitRepository" filter -> ok
 - "PullRequestStatusUpdate" with the "gitRepository" filter -> ok (receiving the correct filtered events to the channel)
 - "GitPush" with the same "gitRepository" filter -> not working (not receiving any event at all to the channel)

I'm using TFS 2015 update 3 and TfsNotificationRelay.tfs2015-v1.18.0. As repository filter, I'm using a simple one word regex.

Could there be an issue there?

Thanks,
Guillaume

**Comment by kria** [comment]
Thanks for an effective bug report!

It looks like I have mixed up the user and repo name arguments when instantiating GitPushNotification [here](https://github.com/kria/TfsNotificationRelay/blob/master/TfsNotificationRelay/EventHandlers/GitPushHandler.cs#L51).
