### ISSUE TITLE
PullRequestComment issue on TFS2017.2 (RC)

### ISSUE THREAD

**Issue by ilengyel** [kria/TfsNotificationRelay#58]
This appears to be a similar issue to #49 where the new update appears to have changed the interface again. Looking in the Event log we get this exception:

    TF53010: The following error has occurred in a Team Foundation component or extension:
    Date (UTC): 7/19/2017 9:57:37 AM
    Machine: <removed>
    Application Domain: /LM/W3SVC/2/ROOT/tfs-8-131449300951399158
    Assembly: Microsoft.TeamFoundation.Framework.Server, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a; v4.0.30319
    Service Host: <removed>
    Process Details:
      Process Name: w3wp
      Process Id: 6132
      Thread Id: 4224
      Account name: <removed>

    Detailed Message: The subscriber TfsNotificationRelay raised an exception while being notified of event Microsoft.VisualStudio.Services.CodeReview.Discussion.WebApi.Events.DiscussionsNotification.
    Exception Message: Method not found: 'Microsoft.TeamFoundation.Git.Server.CommitMetadataAndChanges Microsoft.TeamFoundation.Git.Server.ITeamFoundationGitCommitService.GetCommitManifest(Microsoft.TeamFoundation.Framework.Server.IVssRequestContext, Microsoft.TeamFoundation.Git.Server.ITfsGitRepository, Microsoft.TeamFoundation.Git.Server.Sha1Id)'. (type MissingMethodException)
    Exception Stack Trace:    at DevCore.TfsNotificationRelay.EventHandlers.DiscussionsHandler.CreateNotifications(IVssRequestContext requestContext, DiscussionsNotification args, Int32 maxLines)
       at DevCore.TfsNotificationRelay.EventHandlers.BaseHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties)
       at Microsoft.TeamFoundation.Framework.Server.TeamFoundationEventService.SubscriptionList.Notify(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, String& statusMessage, ExceptionPropertyCollection& properties, Exception& exception)

**Comment by kria** [comment]
I haven't gotten around to trying 2017.2 yet, but the updates usually break something.
