### ISSUE TITLE
Failure loading extensions error

### ISSUE THREAD

**Issue by mhick** [kria/TfsNotificationRelay#8]
After installing on my TFS 2013 server, I received the following error: 

``TF400443: Failure loading extensions of type Microsoft.TeamFoundation.Framework.Server.IEnsureMachineExistsExtension, Microsoft.TeamFoundation.Framework.Server, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.``
``Plugin directory = D:\Program Files\Microsoft Team Foundation Server 12.0\Application Tier\Web Services\bin\Plugins.``

Any thoughts about what be causing it?

**Comment by kria** [comment]
Is that the whole message? I haven't seen that one before. Which update of TFS 2013 are you running? Just to make sure, the plugin doesn't work at all, right?

**Comment by mhick** [comment]
Yes - that's the complete message, and that's all that appears on the screen. TFS won't load at all. We're running TFS 2013.4.

**Comment by kria** [comment]
Where exactly are you getting this error, is it not from the windows log? If you remove the TfsNotificationRelay dlls all is well, but if they are present TFS doesn't work at all? I don't see how that is possible tbh.

**Comment by mhick** [comment]
The message appears in the browser window, without any other information. Watching the Network in Chrome DevTools, I get a 500 Internal Server Error, and the message is the X-TFS-ServiceError value from the response header.

**Comment by mhick** [comment]
Exactly.

**Comment by mhick** [comment]
Argh - just discovered the problem. I had accidentally copied the TfsNotificationRelay files into the /bin folder AND the bin/Plugins folder. Deleted the files from /bin and now it is working. Very excited to start using the plugin!

**Comment by kria** [comment]
Ah, that makes more sense. I'm glad you worked it out! :)
